name: stackedproject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  stacked_services: ^1.1.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.5.1
  golden_toolkit: ^0.15.0
  retrofit_generator: ^6.0.0
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  analyzer: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

